###
http://localhost:8080/actuator
#{
#    "_links": {
#        "self": {
#            "href": "http://localhost:8080/actuator",
#            "templated": false
#        },
#        "health": {
#            "href": "http://localhost:8080/actuator/health",
#            "templated": false
#        },
#        "health-path": {
#            "href": "http://localhost:8080/actuator/health/{*path}",
#            "templated": true
#        }
#    }
#}

### 헬스 상태
http://localhost:8080/actuator/health

#{
#    "status": "UP"
#}

###
http://localhost:8080/actuator/threaddump

### 스프링 컨테이너에 등록된 빈을 보여준다.
http://localhost:8080/actuator/beans

### 웹 서버 shutdown
GET http://localhost:8080/actuator/threaddump

###
GET http://localhost:8080/actuator/health